### ISSUE TITLE
Error: Command failed with exit code: 4

### ISSUE THREAD

**Issue by CodeVoyager-ops** [xoureldeen/Vectras-VM-Android#86]
try again later)
Error: Command failed with exit code: 4

**Comment by epicstudios856** [comment]
show me ss

**Comment by luhaoa** [comment]
This is a network problem. I have other questions to ask. When I use this application to install the android-x86_64-9.0-r2.iso image, even if the installation is successful, there are many problems. For example, when the kernel starts, it prompts "No filesystem could mount root", I suspect the problem is caused by the partition. Which Android ISO can be installed normally? I look forward to your reply. Thank you.

https://github.com/epicstudios856/Vectras-VM-Android/assets/18155749/44b30b98-3d1e-4bc5-b34c-ca9b2b29b6a0

**Comment by xoureldeen** [comment]
fixed
